name: Deploy LibreriaAPI to Server

on:
  push:
    branches:
      - main  # o la rama que uses

jobs:
  deploy:
    name: Deploy to Ubuntu Server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H 104.248.118.8 >> ~/.ssh/known_hosts

    - name: Deploy and Restart with PM2
      run: |
        ssh -i ~/.ssh/id_ed25519 root@104.248.118.8 << 'EOF'
          cd ~/LibreriaApi
          git pull origin main
          source venv/bin/activate
          pm2 restart ecosystem.config.js --update-env
        EOF
